### PR TITLE
Added fetch of application item's data resource

### PR DESCRIPTION
**Pull request by MikeTschudi**
Merged data-resource fetch from 3DScene template with existing boilerplate queryApplication

### CODE REVIEW

**Comment by driskull** [comment]
hey @MikeTschudi what else do we get from `fetchData()`? Do we need to make another network call?

**Comment by MikeTschudi** [comment]
`load()` gets the `http://www.arcgis.com/sharing/content/items/<id>` main part of an item, while `fetchData()` gets the `http://www.arcgis.com/sharing/content/items/<id>/data` data resource part where all of the application configuration values reside. The PortalItem [doc](https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-PortalItem.html#load) implies that `load()` gets all resources, but it doesn't. It would be better if load() had an option to return both pieces to avoid the second network call.

**Comment by driskull** [comment]
@kellyhutchins FYI. I guess it wasn't getting all the app values before?

**Comment by kellyhutchins** [comment]
@driskull  I can look but it must be otherwise it wouldn't be possible to configure and save the config changes for the existing 3d templates.

**Comment by driskull** [comment]
yeah, lets double check. I thought it was working. We can always revert this if needed.

**Comment by kellyhutchins** [comment]
We have the fetchData portion in the 3D template source code so looks like we added this logic to the 3d template source but missed updating the boilerplate.

**Pull request merged**
