### PR TITLE
Development

### LINKED ISSUE #33: Modify the way the template.js code checks to see if app is hosted.
Currently we check if the apps are located in a folder with app or home. This is brittle and causes issues for downloaded apps deployed in location with those folder names.

### PR DESCRIPTION
**Pull request by driskull**
Fixes #33, #39, #40.

@kellyhutchins @iwittenmyer Can you help test & review code?

### CODE REVIEW

**Comment by kellyhutchins** [comment]
I'm going to update the basic viewer template today with these updates so we can test them out in the real environment.

**Comment by driskull** [comment]
sounds like a great idea! :+1:

**Comment by iwittenmyer** [comment]
i can test the basic viewer tomorrow

**Comment by kellyhutchins** [comment]
Ok checked in the update so it'll be ready for testing in the morning.

**Comment by driskull** [comment]
@kellyhutchins don't forget to remove the old templateOptions.js file

**Comment by driskull** [comment]
@kellyhutchins Let me know if its working correctly.

**Comment by iwittenmyer** [comment]
@driskull @kellyhutchins it seems to be working well in the preliminary tests.  The hosted apps are making the correct requests to the custom geocoder and esri gecoder for both suggest and findAddressCandidates

**Comment by driskull** [comment]
@kellyhutchins I've made some code changes. Can we put the latest on the basic viewer for testing. cc @iwittenmyer

**Comment by kellyhutchins** [comment]
@driskull  looks like the updates were just to template.js is that correct?

**Comment by driskull** [comment]
@kellyhutchins Yes.

**Comment by kellyhutchins** [comment]
Ok updated.

**Comment by kellyhutchins** [comment]
Testing looks good - merging.

**Pull request merged**
